### ISSUE TITLE
Could not start upload process. No response from server

### ISSUE THREAD

**Issue by sunmouren** [SnapperGPS/snappergps-app#8]
When I tried to upload data, I received this error message: Could not start upload process. No response from server.
![image](https://github.com/user-attachments/assets/608cb760-9e62-46e1-bf3f-419f22b718b9)

![image](https://github.com/user-attachments/assets/7ac1f835-b7ac-44da-a175-f98ac4200669)

**Comment by JonasBchrt** [comment]
Hi @sunmouren, I am really sorry for the inconvenience.
We are currently moving the SnapperGPS database to a new (larger!) server.
If everything goes well, we are done before the end of this week.
I will update this issue when we are there.
Apologise again - Jonas

**Comment by sunmouren** [comment]
Okay, looking forward to it.

**Comment by sunmouren** [comment]
> Hi @sunmouren, I am really sorry for the inconvenience. We are currently moving the SnapperGPS database to a new (larger!) server. If everything goes well, we are done before the end of this week. I will update this issue when we are there. Apologise again - Jonas

Okay, looking forward to it.

**Comment by sunmouren** [comment]
> Hi @sunmouren, I am really sorry for the inconvenience. We are currently moving the SnapperGPS database to a new (larger!) server. If everything goes well, we are done before the end of this week. I will update this issue when we are there. Apologise again - Jonas

Is it available now?

**Comment by JonasBchrt** [comment]
Yes, it should be available. However, processing may sometimes take longer than normally for the next couple of days.

**Comment by JonasBchrt** [comment]
If uploading still does not work for you or processing does not finish after 2 days or more, feel free to comment here - ideally with a timestamp when you tried.

**Comment by sunmouren** [comment]
> If uploading still does not work for you or processing does not finish after 2 days or more, feel free to comment here - ideally with a timestamp when you tried.

I have been able to upload the data, thank you.
